
Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = Glob('*.c')

CPPPATH = [RTT_ROOT + '/Driver/include']

group = DefineGroup('driver',src,depend = [''],CPPPATH = CPPPATH)

Return('group')