# for algorithm build

Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = Glob('*.c')
CPPPATH = [RTT_ROOT + '/Algorithm/include']
group = DefineGroup('Algorithm',src,depend = [''],CPPPATH = CPPPATH)

Return('group')